---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: openshift-gitops
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    path: setup/kyverno
    repoURL: https://github.com/ch-stark/gatekeeper-kyverno-policyset.git
    targetRevision: HEAD
  ignoreDifferences:
  - kind: "Namespace"  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: false
