apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: kyverno-deploy-bestpractise
placementBindingDefaults:
  name: kyverno-deploy-bestpractise
policyDefaults:
  informKyvernoPolicies: true
  configurationPolicyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: kyverno-deploy-bestpractise
  remediationAction: enforce
  severity: medium
  deploy-bestpractises:
    - kyverno-deploy-bestpractise
  standards:
    - generic
  placementPath:  
    - placement.yaml
policies:
- name: restrict-annotations
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_annotations
- name: base-images
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/base_images  
- name: affinity
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/affinity
- name: routes
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/routes 
- name: poddisruptionbudget  
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/poddisruptionbudget  
- name: securitycontextconstraint
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/security-context-contraint          
policyset:
  - description: kyverno-deploy-bestpractise to apply set of kyverno-policies.
    name: kyverno-deploy-bestpractise
    placement:
      placementPath: placement.yaml

    


    
   


