apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: kyverno-policyset
placementBindingDefaults:
  name: kyverno-policyset
policyDefaults:
  policyAnnotations: {"policy.open-cluster-management.io/disable-templates": "true"}
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: kyverno-policyset
  remediationAction: enforce
  severity: medium
  policySets:
    - kyverno-policyset
  standards:
    - generic
  placementPath:  
    - placement.yaml
policies:
- name: restrict-annotations
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_annotations
- name: restrict-automount-sa-token
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_automount_sa_token
- name: restrict-binding-clusteradmin
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict-binding-clusteradmin
- name: restrict-clusterrole-nodesproxy
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict-clusterrole-nodesproxy
- name: restrict-controlplane-scheduling
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_controlplane_scheduling
- name: restrict-escalation-verbs-roles
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict-escalation-verbs-roles
- name: restrict-ingress-classes
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_ingress_classes
- name: restrict-ingress-defaultbackend
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_ingress_defaultbackend
- name: restrict-ingress-host
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_ingress_host
- name: restrict-ingress-wildcard
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict-ingress-wildcard
- name: restrict-loadbalancer
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_loadbalancer
- name: restrict-node-selection
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_node_selection
- name: restrict-pod-count-per-node
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_pod_count_per_node
- name: restrict-secret-role-verbs
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict-secret-role-verbs
- name: restrict-secrets-by-label
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_secrets_by_label
- name: restrict-secrets-by-name
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_secrets_by_name
- name: restrict-service-account
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict-service-account
- name: restrict-service-port-range
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict_service_port_range
- name: restrict-wildcard-resources
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict-wildcard-resources
- name: restrict-wildcard-verbs
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/restrict-wildcard-verbs
- name: networking-block-nodeport-services
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/networking/block-nodeport-services
- name: networking-httpsonly
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/networking/httpsonly
- name: resource-exhaustion
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/resource-exhaustion/disallow-self-provisioner
- name: authorization
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/authorization
- name: authorizationhost-namespaces
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/authorization/host-namespaces
- name: authorizationhost-protect-default-scc
  categories:
    - setup
  controls: 
    - setup
  disabled: false
  manifests:
    - path: input/authorization/protect-default-scc
policySets:
  - description: kyverno-policyset to apply set of kyverno-policies.
    name: kyverno-policyset
    placement:
      placementPath: placement.yaml

    


    
   


